-- phpMyAdmin SQL Dump
-- version OVH
-- https://www.phpmyadmin.net/
--
-- Hôte : mysql51-86.perso
-- Généré le :  Dim 07 mars 2021 à 13:16
-- Version du serveur :  5.6.50-log
-- Version de PHP :  7.0.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `orguepay`
--

-- --------------------------------------------------------

--
-- Structure de la table `inventaire_clavier1`
--

CREATE TABLE `inventaire_clavier1` (
  `id` int(11) NOT NULL,
  `c1` varchar(100) DEFAULT NULL,
  `c1_notes` varchar(2) DEFAULT NULL,
  `c1_1_nom` varchar(255) DEFAULT NULL,
  `c1_1_hauteur` varchar(255) DEFAULT NULL,
  `c1_1_spec` varchar(255) DEFAULT NULL,
  `c1_2_nom` varchar(255) DEFAULT NULL,
  `c1_2_hauteur` varchar(255) DEFAULT NULL,
  `c1_2_spec` varchar(255) DEFAULT NULL,
  `c1_3_nom` varchar(255) DEFAULT NULL,
  `c1_3_hauteur` varchar(255) DEFAULT NULL,
  `c1_3_spec` varchar(255) DEFAULT NULL,
  `c1_4_nom` varchar(255) DEFAULT NULL,
  `c1_4_hauteur` varchar(255) DEFAULT NULL,
  `c1_4_spec` varchar(255) DEFAULT NULL,
  `c1_5_nom` varchar(255) DEFAULT NULL,
  `c1_5_hauteur` varchar(255) DEFAULT NULL,
  `c1_5_spec` varchar(255) DEFAULT NULL,
  `c1_6_nom` varchar(255) DEFAULT NULL,
  `c1_6_hauteur` varchar(255) DEFAULT NULL,
  `c1_6_spec` varchar(255) DEFAULT NULL,
  `c1_7_nom` varchar(255) DEFAULT NULL,
  `c1_7_hauteur` varchar(255) DEFAULT NULL,
  `c1_7_spec` varchar(255) DEFAULT NULL,
  `c1_8_nom` varchar(255) DEFAULT NULL,
  `c1_8_hauteur` varchar(255) DEFAULT NULL,
  `c1_8_spec` varchar(255) DEFAULT NULL,
  `c1_9_nom` varchar(255) DEFAULT NULL,
  `c1_9_hauteur` varchar(255) DEFAULT NULL,
  `c1_9_spec` varchar(255) DEFAULT NULL,
  `c1_10_nom` varchar(50) DEFAULT NULL,
  `c1_10_hauteur` varchar(100) DEFAULT NULL,
  `c1_10_spec` varchar(255) DEFAULT NULL,
  `c1_11_nom` varchar(50) DEFAULT NULL,
  `c1_11_hauteur` varchar(100) DEFAULT NULL,
  `c1_11_spec` varchar(255) DEFAULT NULL,
  `c1_12_nom` varchar(50) DEFAULT NULL,
  `c1_12_hauteur` varchar(100) DEFAULT NULL,
  `c1_12_spec` varchar(255) DEFAULT NULL,
  `c1_13_nom` varchar(50) DEFAULT NULL,
  `c1_13_hauteur` varchar(100) DEFAULT NULL,
  `c1_13_spec` varchar(255) DEFAULT NULL,
  `c1_14_nom` varchar(50) DEFAULT NULL,
  `c1_14_hauteur` varchar(100) DEFAULT NULL,
  `c1_14_spec` varchar(255) DEFAULT NULL,
  `c1_15_nom` varchar(50) DEFAULT NULL,
  `c1_15_hauteur` varchar(100) DEFAULT NULL,
  `c1_15_spec` varchar(255) DEFAULT NULL,
  `c1_16_nom` varchar(50) DEFAULT NULL,
  `c1_16_hauteur` varchar(100) DEFAULT NULL,
  `c1_16_spec` varchar(255) DEFAULT NULL,
  `c1_17_nom` varchar(50) DEFAULT NULL,
  `c1_17_hauteur` varchar(100) DEFAULT NULL,
  `c1_17_spec` varchar(255) DEFAULT NULL,
  `c1_18_nom` varchar(50) DEFAULT NULL,
  `c1_18_hauteur` varchar(100) DEFAULT NULL,
  `c1_18_spec` varchar(255) DEFAULT NULL,
  `c1_19_nom` varchar(50) DEFAULT NULL,
  `c1_19_hauteur` varchar(100) DEFAULT NULL,
  `c1_19_spec` varchar(255) DEFAULT NULL,
  `c1_20_nom` varchar(50) DEFAULT NULL,
  `c1_20_hauteur` varchar(100) DEFAULT NULL,
  `c1_20_spec` varchar(255) DEFAULT NULL,
  `c1_21_nom` varchar(50) DEFAULT NULL,
  `c1_21_hauteur` varchar(100) DEFAULT NULL,
  `c1_21_spec` varchar(255) DEFAULT NULL,
  `c1_22_nom` varchar(50) DEFAULT NULL,
  `c1_22_hauteur` varchar(100) DEFAULT NULL,
  `c1_22_spec` varchar(255) DEFAULT NULL,
  `c1_23_nom` varchar(50) DEFAULT NULL,
  `c1_23_hauteur` varchar(100) DEFAULT NULL,
  `c1_23_spec` varchar(255) DEFAULT NULL,
  `c1_24_nom` varchar(50) DEFAULT NULL,
  `c1_24_hauteur` varchar(100) DEFAULT NULL,
  `c1_24_spec` varchar(255) DEFAULT NULL,
  `c1_25_nom` varchar(50) DEFAULT NULL,
  `c1_25_hauteur` varchar(100) DEFAULT NULL,
  `c1_25_spec` varchar(255) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `inventaire_clavier1`
--

INSERT INTO `inventaire_clavier1` (`id`, `c1`, `c1_notes`, `c1_1_nom`, `c1_1_hauteur`, `c1_1_spec`, `c1_2_nom`, `c1_2_hauteur`, `c1_2_spec`, `c1_3_nom`, `c1_3_hauteur`, `c1_3_spec`, `c1_4_nom`, `c1_4_hauteur`, `c1_4_spec`, `c1_5_nom`, `c1_5_hauteur`, `c1_5_spec`, `c1_6_nom`, `c1_6_hauteur`, `c1_6_spec`, `c1_7_nom`, `c1_7_hauteur`, `c1_7_spec`, `c1_8_nom`, `c1_8_hauteur`, `c1_8_spec`, `c1_9_nom`, `c1_9_hauteur`, `c1_9_spec`, `c1_10_nom`, `c1_10_hauteur`, `c1_10_spec`, `c1_11_nom`, `c1_11_hauteur`, `c1_11_spec`, `c1_12_nom`, `c1_12_hauteur`, `c1_12_spec`, `c1_13_nom`, `c1_13_hauteur`, `c1_13_spec`, `c1_14_nom`, `c1_14_hauteur`, `c1_14_spec`, `c1_15_nom`, `c1_15_hauteur`, `c1_15_spec`, `c1_16_nom`, `c1_16_hauteur`, `c1_16_spec`, `c1_17_nom`, `c1_17_hauteur`, `c1_17_spec`, `c1_18_nom`, `c1_18_hauteur`, `c1_18_spec`, `c1_19_nom`, `c1_19_hauteur`, `c1_19_spec`, `c1_20_nom`, `c1_20_hauteur`, `c1_20_spec`, `c1_21_nom`, `c1_21_hauteur`, `c1_21_spec`, `c1_22_nom`, `c1_22_hauteur`, `c1_22_spec`, `c1_23_nom`, `c1_23_hauteur`, `c1_23_spec`, `c1_24_nom`, `c1_24_hauteur`, `c1_24_spec`, `c1_25_nom`, `c1_25_hauteur`, `c1_25_spec`) VALUES
(1, 'Grand orgue', '56', 'Montre', '16\\\'', '', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte', '8\\\'', 'C3 (ajout de 1982, appel au pied)', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte', '4\\\'', '', 'Nasard', '2\\\'2/3', '', 'Doublette', '2\\\'', '', 'Flûte', '2\\\'', '', 'Tierce', '1\\\'3/5', '', 'Plein-jeu', 'IV', '', 'Cymbale', 'IV', NULL, 'Trompette', '8\\\'', 'en chamade', 'Clairon', '4\\\'', 'en chamade', '', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2, 'Grand orgue', '61', 'Montre', '16\\\'', '', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Principal', '8\\\'', '', 'Diapason', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Grosse quinte', '5\\\'1/3', '', 'Prestant', '4\\\'', '', 'Flûte', '4\\\'', '', 'Grande tierce', '3\\\'1/5', '', 'Quinte flûte', '2\\\'2/3', '', 'Doublette', '2\\\'', '', 'Quarte', '2\\\'', '', 'Tierce', '1\\\'3/5', '', 'Cornet', 'V', 'Fa2', 'Grande fourniture', 'II-IV', '', 'Fourniture', 'IV', '', '1ère Trompette', '8\\\'', NULL, '2ème Trompette', '8\\\'', '', 'Clairon 4\\\'', NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL),
(3, 'Grand-Orgue', '50', 'Montre', '8\\\'', '', 'Bourdon à cheminée', '8\\\'', '', 'Prestant', '4\\\'', '', 'Nasard', '2\\\'2/3', '', 'Doublette', '2\\\'', '', 'Tiercyne', '1\\\'3/5', '', 'Fourniture', 'III-V', '', 'Cymbale', 'III', '', 'Cornet', 'V', 'C3', 'Trompette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4, 'Grand-Orgue', '56', 'Principal', '8\\\'', NULL, 'Bourdon', '8\\\'', NULL, 'Prestant', '4\\\'', NULL, 'Nasard', '2\\\'2/3', NULL, 'Doublette', '2\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5, 'Positif', '54', 'Montre', '8\\\'', NULL, 'Bourdon', '8\\\'', NULL, 'Salicional', '8\\\'', NULL, 'Prestant', '4\\\'', NULL, 'Flûte douce', '4\\\'', NULL, 'Quinte', '3\\\'', NULL, 'Doublette', '2\\\'', NULL, 'Plein-jeu', 'IV', NULL, 'Trompette', '8\\\'', NULL, 'Cromorne', '8\\\'', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', NULL, 'Montre', '8\\\'', NULL, 'Flûte harmonique', '8\\\'', NULL, 'Prestant', '4\\\'', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7, 'Grand Orgue', '56', 'Principal ', '8\\\'', NULL, 'Rohrflöte', '8\\\'', '', 'Octava', '4\\\'', '', 'Octava', '2\\\'', '', 'Sesquialtera', 'II', '', 'Mixtur', 'IV', '', 'Trompette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8, 'Grand-Orgue', '54', 'Quintaton', '16\\\'', 'C3', 'Montre', '8\\\'', '', 'Flûte', '8\\\'', '', 'Solicional', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-jeu', 'III-V', '5e rang muet', 'Trompette', '8\\\'', 'basses/dessus C#3', 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(9, 'Grand-Orgue', '56', 'Montre', '16\\\'', NULL, 'Bourdon', '16\\\'', NULL, 'Montre', '8\\\'', NULL, 'Flûte harmonique', '8\\\'', NULL, 'Salicional', '8\\\'', NULL, 'Bourdon', '8\\\'', NULL, 'Grosse Quinte', '5\\\'1/3', NULL, 'Prestant', '4\\\'', NULL, 'Flûte', '4\\\'', '', 'Grosse Tierce', '3\\\'1/5', NULL, 'Quinte', '2\\\'2/3', NULL, 'Doublette', '2\\\'', NULL, 'Plein-jeu', 'IV', NULL, 'Cymbale', 'IV', '', 'Cornet', 'V', 'C2', 'Bombarde', '16\\\'', NULL, 'Trompette', '8\\\'', NULL, 'Clairon', '4\\\'', NULL, 'Trompette chamade', '8\\\'', NULL, 'Clairon chamade', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(10, 'Positif', '56', 'Flûte', '8\\\'', 'C1-H1 communs avec le Bourdon', 'Bourdon à cheminée', '8\\\'', NULL, 'Salicional', '8\\\'', NULL, 'Dulciane', '4\\\'', NULL, 'Flûte douce', '4\\\'', NULL, 'Nasard', '2\\\'2/3', NULL, 'Doublette', '2\\\'', NULL, 'Tierce', '1\\\'3/5', NULL, 'Piccolo', '1\\\'', NULL, 'Plein-Jeu', 'V', NULL, 'Trompette', '8\\\'', NULL, 'Clarinette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11, 'Grand-Orgue', '61', 'Bourdon', '16\\\'', NULL, 'Montre', '8\\\'', NULL, 'Flûte harmonique', '8\\\'', NULL, 'Bourdon', '8\\\'', NULL, 'Prestant', '4\\\'', NULL, 'Doublette', '2\\\'', 'en attente', 'Plein-jeu', 'IV', '', 'Cromorne', '8\\\'', '', 'Tuba harmonique', '8\\\'', '', 'Chamade', '8\\\'', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12, 'Grand-Orgue', '54', 'Bourdon', '16\\\'', NULL, 'Montre', '8\\\'', NULL, 'Bourdon', '8\\\'', NULL, 'Flûte', '8\\\'', 'en bois', 'Prestant', '4\\\'', NULL, 'Flûte', '4\\\'', 'en bois', 'Doublette', '2\\\'', NULL, 'Plein-jeu', 'IV', NULL, 'Trompette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(13, 'Grand-Orgue', '61', 'Montre', '16\\\'', NULL, 'Bourdon', '16\\\'', NULL, 'Montre', '8\\\'', NULL, 'Principal', '8\\\'', NULL, 'Flûte harmonique', '8\\\'', NULL, 'Diapason', '8\\\'', NULL, 'Bourdon', '8\\\'', NULL, 'Grosse Quinte', '5\\\'1/3', NULL, 'Prestant', '4\\\'', NULL, 'Flûte', '4\\\'', NULL, 'Grosse Tierce', '3\\\'1/5', NULL, 'Quinte Flûte', '2\\\'2/3', NULL, 'Doublette', '2\\\'', NULL, 'Quarte de Nasard', '2\\\'', NULL, 'Tierce', '1\\\'3/5', NULL, 'Grosse Fourniture', 'II-IV', NULL, 'Fourniture', 'IV', NULL, 'Cymbale', 'IV', NULL, 'Cornet', 'V', 'F2', '1ère Trompette', '8\\\'', NULL, '2ème Trompette', '8\\\'', NULL, 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(14, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', NULL, 'Montre', '8\\\'', NULL, 'Flûte harmonique', '8\\\'', NULL, 'Bourdon', '8\\\'', NULL, 'Montre', '4\\\'', NULL, 'Plein-jeu', 'IV', NULL, 'Trompette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15, 'Grand orgue', '56', 'Bourdon', '16\\\'', NULL, 'Montre', '8\\\'', NULL, 'Bourdon', '8\\\'', NULL, 'Flûte harmonique', '8\\\'', NULL, 'Salicional', '8\\\'', NULL, 'Prestant', '4\\\'', NULL, 'Nasard', '2\\\'2/3', 'extrait du Plein-jeu', 'Plein-jeu', 'II-V', NULL, 'Trompette', '8', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16, 'Positif', '48', 'Bourdon', '8\\\'', '', 'Montre', '4\\\'', '', 'Flûte à biberon', '4\\\'', '', 'Nazard', '2\\\'2/3', '', 'Doublette', '2\\\'', '', 'Tierce', '1\\\'3/5', '', 'Larigot', '1\\\'1/3', '', 'Fourniture', 'III', '', 'Cymbale', 'II', '', 'Cromorne', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-jeu', 'V', '', 'Cornet', 'V', 'C3', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18, 'Grand-Orgue', '56', 'Montre', '16\\\'', '', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Flûte ouverte', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte ouverte', '4\\\'', '', 'Grosse Tierce', '3\\\'1/5', '', 'Nasard', '2\\\'2/3', '', 'Doublette', '2\\\'', '', 'Tierce', '1\\\'3/5', '', 'Grosse Fourniture', 'II', '', 'Fourniture', 'III', '', 'Cymbale', 'IV', '', 'Cornet', 'V', 'C3', 'Bombarde', '16\\\'', '', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(124, 'Clavier', '54', 'Montre', '8\'', NULL, 'Bourdon', '8\'', 'jusqu\'à E3', 'Flûte harmonique', '8\'', 'F3', 'Voix céleste', '8\'', 'C2', 'Prestant', '4\'', NULL, 'Octavin', '2\'', NULL, 'Trompette', '8\'', NULL, 'Hautbois', '8\'', 'C3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19, 'Grand-Orgue', '56', 'Violoncelle', '16\\\'', '', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte', '8\\\'', '', 'Salicional', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-Jeu', 'III-VI', '', 'Fourniture', 'VII', '', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(20, 'Positif', '56', 'Viole', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Montre', '4\\\'', '', 'Flûte à cheminée', '4\\\'', '', 'Nazard', '2\\\'2/3', '', 'Doublette', '2\\\'', '', 'Tierce', '1\\\'3/5', '', 'Plein-jeu', 'V', '', 'Cromorne', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(21, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte à cheminée', '8\\\'', '', 'Prestant', '4\\\'', '', 'Grosse Fourniture', 'II', '', 'Mixtur', 'IV', '', 'Cornet', 'IV', 'F2', 'Trompette chamade', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(22, 'Clavier', '56', 'Prestant', '8\\\'', 'B/D', 'Bourdon', '8\\\'', 'B/D', 'Octaaf', '4\\\'', 'B/D, extension', 'Fluit', '4\\\'', 'B/D, extension', 'Doublette', '2\\\'', 'B/D, extension', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(29, 'Grand-Orgue', '56', 'Principal', '16\\\'', 'C2', 'Bourdon', '16\\\'', NULL, 'Montre', '8\\\'', NULL, 'Flûte harmonique', '8\\\'', NULL, 'Cor de nuit', '8\\\'', NULL, 'Mélophone', '8\\\'', NULL, 'Prestant', '4\\\'', NULL, 'Doublette', '2\\\'', NULL, 'Plein-jeu', 'III-IV', '', 'Trompette', '8\\\'', NULL, 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(23, 'Positif', '56', 'Bourdon', '16\\\'', 'D', 'Flûte harmonique', '8\\\'', 'D', 'Bourdon', '8\\\'', 'B/D', 'Violoncelle', '8\\\'', 'B/D', 'Flûte octaviante', '4\\\'', 'B/D', '', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(24, 'Grand-Orgue', '', 'Montre', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte à cheminée', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein jeu', 'IV', '', 'Trompette', '8\\\'', '', '', '', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(25, 'Positif', '56', 'Bourdon', '8\\\'', '', 'Flûte allemande', '8\\\'', 'G3', 'Flûte à biberon', '4\\\'', '', 'Flûte', '2\\\'', '', 'Tierce', '1\\\'3/5', '', 'Larigot', '1\\\'1/3', '', 'Cymbale', 'III', '', 'Trompette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(26, 'Positif', '56', 'Bourdon', '8\\\'', '', 'Montre', '4\\\'', '', 'Flûte à cheminée', '4\\\'', '', 'Nasard', '2\\\'2/3', '', 'Doublette', '2\\\'', '', 'Tierce', '1\\\'3/5', '', 'Plein-Jeu', 'V', '', 'Cromorne', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(27, 'Clavier', '54', 'Principal', '8\\\'', 'C2', 'Gedackt', '8\\\'', '', 'Octava', '4\\\'', '', 'Rohrflöte', '4\\\'', '', 'Octava', '2\\\'', 'B/D C#3', 'Quinta', '1\\\'1/3', 'B/D C#3', 'Sifflöte', '1', 'B/D C#3', 'Sesquialter', 'II', 'C#3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(28, 'Grand-Orgue', '56', 'Montre', '16\\\'', '', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte douce', '4\\\'', '', 'Doublette', '2\\\'', '', 'Fourniture', 'IV', '', 'Cymbale', 'IV', '', 'Cornet', 'V', 'F2', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(30, 'Grand Orgue', '56', 'Bourdon', '16\\\'', NULL, 'Montre', '8\\\'', NULL, 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', NULL, 'Nazard', '2\\\' 2/3', '', 'Fourniture', 'V', NULL, '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(31, 'Grand orgue', '54', 'Montre', '16\\\'', 'A1', 'Montre', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-jeu', 'IV', '', 'Cornet', 'IV', 'C3', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(32, 'Grand orgue', '54', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Salicional', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-jeu', 'III', '', 'Trompette', '8\\\'', NULL, 'Clairon ', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(33, 'Grand orgue', '56', 'Quintaton', '16\\\'', '', 'Montre', '8\\\'', '', 'Grosse flute', '8\\\'', '', 'Sesquialtera', 'II', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(34, 'Grand-Orgue', '56', 'Montre', '8\\\'', '', 'Salicional', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4', '', 'Plein-Jeu', 'IV', '', 'Cornet', 'V', 'F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(35, 'Grand-Orgue', '56', 'Montre', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-Jeu', 'III', '', 'Cornet', 'V', 'F2', 'Trompette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(36, 'Grand-Orgue', '54', 'Flûte', '8\\\'', NULL, 'Bourdon', '8\\\'', NULL, 'Prestant', '4\\\'', NULL, 'Doublette', '2\\\'', NULL, 'Plein jeu', 'II-V', '', 'Trompette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(45, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte harmonique', '8\\\'', NULL, 'Bourdon', '8\\\'', '', 'Salicional', '8\\\'', '', 'Violoncelle', '8\\\'', '', 'Prestant', '4\\\'', '', 'Quinte', '2\\\'2/3', '', 'Doublette', '2\\\'', NULL, 'Fourniture', 'IV', '', 'Cymbale', 'III', '', 'Bombarde', '16\\\'', '', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(37, 'Positif', '56', 'Bourdon', '8\\\'', 'en bois', 'Principal', '4\\\'', '', 'Flûte à cheminée', '4\\\'', '', 'Nasard', '2\\\'2/3', '', 'Flûte conique', '2\\\'', '', 'Tierce', '1\\\'3/5', '', 'Larigot', '1\\\'1/3', '', 'Sifflet', '1\\\'', '', 'Mixture', 'IV-V', '', 'Cromorne', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(39, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte octaviante', '4\\\'', '', 'Doublette', '2\\\'', '', 'Fourniture', 'IV', '', 'Basson', '16\\\'', '', 'Trompette harmonique', '8\\\'', '', 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(40, 'Grand-Orgue', '56', 'Montre', '16\\\'', '', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte douce', '4\\\'', '', 'Quinte', '2\\\'2/3', '', 'Doublette', '2\\\'', '', 'Tierce', '1\\\'3/5', '', 'Grosse Fourniture', 'III', '', 'Plein-Jeu', 'IV', '', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', '', 'Cromorne', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(41, 'Grand-Orgue', '56', 'Montre', '16\\\'', '', 'Montre', '8\\\'', '', 'Flute ouvert', '8\\\'', '', 'Gambe', '8\\\'', '', 'Principal', '8\\\'', 'dessus', 'Prestant', '4\\\'', '', 'Quinte', '2\\\'2/3', '', 'Nasard', '2\\\'2/3', '= Positif', 'Doublette', '2\\\'', '', 'Quarte de Nasard', '2\\\'', '= Positif', 'Tierce', '1\\\'3/5', '= Positif', 'Larigot', '1\\\'1/3', '= Positif', 'Fourniture', 'IV', '', 'Cimbale', 'III', NULL, 'Cornet', 'V', 'C3', 'Trompette', '16\\\'', '', 'Trompette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(42, 'Grand-Orgue', '54', 'Bourdon', '16\\\'', 'B/D/ F3', 'Flûte', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Gambe', '8\\\'', '', 'Prestant', '4\\\'', 'B/D/ F3', 'Salicional', '4\\\'', 'B/D/ F3', 'Nazard', '2\\\'2/3', '', 'Doublette', '2\\\'', 'B/D/ F3', 'Trompette', '8\\\'', '16\\\' F#4', 'Clairon', '4\\\'', '8\\\' F#4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(43, 'Grand-Orgue', '54', 'Montre', '16\\\'', '', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Salicional', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte', '4\\\'', '', 'Doublette', '2\\\'', '', 'Fourniture', 'IV', '', 'Cymbale', 'III', '', 'Cornet', 'V', 'C3', 'Bombarde', '16\\\'', '', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', '', 'Cromorne', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(44, 'Grand-Orgue', '56', 'Open Diapason', '8\\\'', '', 'Lieblich Gedacht', '8\\\'', '', 'Gamba', '8\\\'', '', 'Gemshorn', '4\\\'', '', '', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(46, NULL, NULL, '', '', '', '', '', '', NULL, NULL, '', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL),
(47, 'Grand-Orgue', '61', 'Montre', '16\\\'', '', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Fugara', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Fourniture', 'IV', '', 'Cymbale', 'III', '', 'Cornet', 'III-V', '', 'Bombarde', '16\\\'', '', '1e Trompette', '8\\\'', '', '2e Trompette', '8\\\'', '= Pédale', 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(48, 'Grand-Orgue', '56', 'Montre', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Nasard', '2\\\'2/3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(49, 'Grand-Orgue', '56', 'Montre', '8\\\'', '', 'Flûte à cheminée', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte', '2\\\'', '', 'Mixtur', 'IV', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(60, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Principal', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-Jeu', 'V', '5e rang muet dans l\\\'aigu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50, 'Clavier', '54', 'Flûte', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Voix céleste', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Cornet', 'IV', 'dessus', 'Trompette', '8\\\'', '', 'Clairon-Hautbois', '4\\\'-8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(51, 'Grand-Orgue', '56', 'Montre', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Sesquilatera', 'II', '', 'Plein-Jeu', '', '', 'Trompette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(52, 'Grand-Orgue', '61', 'Montre', '8\\\'', '', 'Flûte à cheminée', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte', '4\\\'', '', 'Doublette', '2', '', 'Plein-Jeu', 'IV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(53, 'Grand-Orgue', '56', 'Montre', '8\\\'', '', 'Flûte', '8\\\'', '', 'Bourdon', NULL, '', 'Prestant', NULL, '', 'Flûte', '4\\\'', '', 'Nasard', '2\\\'2/3', '', 'Doublette', '2\\\'', '', 'Tierce', '1\\\'3/5', '', 'Plein-Jeu', 'IV', '', 'Trompette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(54, 'Grand-Orgue', '61', 'Montre', '16\\\'', '', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-Jeu', 'V', '', 'Cymbale', 'IV', '', 'Cornet', 'V', 'F2', 'Bombarde', '16\\\'', '', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(55, 'Grand Orgue', '56', 'Montre', '8\\\'', '', 'Bourdon', '8\\\'', NULL, 'Prestant', '4\\\'', NULL, 'Doublette', '2\\\'', '', 'Larigot', '1\\\'1/3', NULL, 'Fourniture', 'IV', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(56, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(57, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(58, 'Grand-Orgue', '56', 'Montre', '8\\\'', NULL, 'Flûte à cheminée ', '8\\\'', NULL, 'Prestant ', '4\\\'', NULL, 'Flûte', '2\\\'', NULL, 'Tercian', 'II', '1\\\'1/3 + 4/5\\\'', 'Mixtur', 'IV', NULL, 'Cymbale', 'III', NULL, 'Trompette', '8\\\'', NULL, 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(59, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte', '4\\\'', '', 'Doublette', '2\\\'', '', 'Fourniture', 'V', '', 'Trompette', '8\\\'', '', 'Cromorne', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(61, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Nasard', '2\\\'2/3', '', '(deux jeux en attente)', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(62, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-Jeu', 'IV', '', 'Trompette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(63, 'Grand-Orgue', '61', 'Montre', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte', '2\\\'', '', 'Mixtur', 'IV', '', 'Cornet', 'III', '', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(64, 'Grand-Orgue', '54', 'Montre', '8\\\'', '', 'Prestant', '4\\\'', '', 'Quinte', '2\\\'2/3', '', 'Fourniture', 'IV', '', 'Trompette royale', '4/8\\\'', 'en chamade', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(65, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Salicional', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(66, 'Grand-Orgue', '54', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Salicional', '8\\\'', '', 'Prestant', '4\\\'', NULL, 'Doublette', '2\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(67, 'Oberwerk', '54', 'Gedackt', '8\\\'', '', 'Octava', '4\\\'', '', 'Rohrflöte', '4\\\'', '', 'Nazat', '2\\\'2/3', '', 'Octava', '2\\\'', '', 'Tiertia', '1\\\'3/5', '', 'Sifflöte', '1\\\'', '', 'Cimbel', 'III', '', 'Vox humana', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(68, 'Grand-Orgue', '56', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Cymbale', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(69, 'Grand-Orgue', '56', 'Montre', '8\\\'', '', 'Flûte à cheminée', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Fourniture', 'IV', '', 'Cromorne', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(70, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Quintaton', '16\\\'', 'G2', 'Montre', '8\\\'', '', 'Kéraulophone', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Solicional', '8\\\'', '', 'Prestant', '4\\\'', '', 'Octavin', '2\\\'', '', 'Plein-Jeu', 'III', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(71, 'Grand-Orgue', '53', 'Montre', '8\\\'', '', 'Flûte à cheminée', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte à cheminée', '4\\\'', '', 'Nasard', '2\\\'2/3', '', 'Doublette', '2\\\'', '', 'Tierce', '1\\\'3/5', '', 'Quinte', '1\\\'1/3', '', 'Mixture', 'IV', '', 'Trompette', '8\\\'', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(72, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte douce', '4\\\'', '', 'Grosse Tierce', '3\\\'1/5', '', 'Quinte', '2\\\'2/3', '', 'Doublette', '2\\\'', '', 'Flûte', '2\\\'', '', 'Tierce', '1\\\'3/5', '', 'Fourniture', 'IV', '', 'Cornet', 'V', 'C3', 'Trompette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(73, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-Jeu', 'IV', '', 'Cromorne', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(74, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Principal', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(75, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte', '4\\\'', '', 'Doublete', '2\\\'', '', 'Piccolo', '1\\\'', '', 'Plein-Jeu', 'IV', '', 'Cromorne', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(76, 'Grand-Orgue', '56', 'Montre', '16\\\'', 'prévue', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-Jeu', 'IV', '', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(77, 'Clavier expressif', '56', 'Bourdon', '16\\\'', 'F3', 'Flûte harmonique', '8\\\'', 'B/D', 'Bourdon', '8\\\'', 'B/D', 'Violoncelle', '8\\\'', 'B/D', 'Prestant', '4\\\'', '', 'Fourniture', 'II', '', 'Trompette', '8\\\'', 'B/D', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(78, 'POSITIF', '56', 'Flûte à Cheminée', '8\\\'', NULL, 'Viola de Gambe', '8\\\'', NULL, 'Unda Maris', '4\\\'', NULL, 'Gemshorm', '4\\\'', NULL, 'Nasard', '2 2/3', NULL, 'Principal', '2\\\'', NULL, 'Tierce', '1 1/3', NULL, 'Trompette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(79, 'Grand-Orgue', '54', 'Keraulophone', '8\\\'', '', 'Flute', '8\\\'', NULL, 'Bourdon', '8\\\'', NULL, 'Gambe', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', NULL, 'Trompette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(80, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(81, 'Positif', '56', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte', '4\\\'', '', 'Nazard', '2\\\'2/3', '', 'Doublette', '2\\\'', '', 'Tierce', '1\\\'3/5', '', 'Larigot', '1\\\'1/3', '', 'Plein-Jeu', 'V', '', 'Cromorne', '8\\\'', '', 'Régale', '8\\\'', 'en chamade', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(82, 'Grand-Orgue', '56', 'Montre', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte', '2\\\'', NULL, 'Mixtur', 'IV', '', 'Cymbale', 'III', '', 'Tercian', 'II', '', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(83, 'Grand-Orgue', '56', 'Montre', '8\\\'', '', 'Flûte à cheminée', '8\\\'', '', 'Prestant', '4\\\'', '', 'Mixture', 'IV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(84, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte', '8\\\'', '', 'Prestant', '4\\\'', '', 'Plein-Jeu', 'V', NULL, '', '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(92, 'Grand-Orgue', '58', 'Quintade', '16\\\'', '', 'Montre', '8\\\'', '', 'Bourdon', '8\\\'', '= Résonance', 'Flûte ouverte', '8\\\'', '= Résonance', 'Prestant', '4\\\'', '', 'Flûte d\\\'allemand', '4\\\'', '= Résonance', 'Quinte', '2\\\'2/3', '', 'Doublette', '2\\\'', '', 'Flûte', '2\\\'', '= Résonance', 'Tiercelette', '1\\\'3/5', '', 'Flageolet', '1\\\'', '= Résonance', 'Fourniture', 'II', '', 'Mixture', 'IV', '', 'Douçaine', '16\\\'', '= Résonance', 'Trommete', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(85, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(86, 'Positif', '51', 'Bourdon', '8\\\'', '', 'Gambe', '8\\\'', '', 'Montre', '4\\\'', '', 'Nasard', '2\\\'2/3', '', 'Doublette', '2\\\'', '', 'Tierce', '1\\\'3/5', '', 'Cymbale', 'III', '', 'Cromorne', '8\\\'', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(87, 'Clavier', '56', 'Bourdon', '8', 'basses', 'Flûte harmonique', '8', 'dessus', 'Violoncelle', '8', 'basses et dessus', 'Voix céleste', '8', 'dessus', 'Flûte octaviante', '4', 'basses et dessus', 'Trompette', '8', 'basses et dessus', 'Clariton', NULL, 'basses et dessus', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(88, 'Grand Orgue', '56', 'Bourdon ', '16', NULL, 'Montre', '8', NULL, 'Salicional', '8', NULL, 'Bourdon', '8', NULL, 'Flûte harmonique', '8', NULL, 'Prestant', '4', NULL, 'Doublette', '2', NULL, 'Plain Jeu', 'IV', NULL, 'Trompette', '8', NULL, 'Cromorne', '8', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `inventaire_clavier1` (`id`, `c1`, `c1_notes`, `c1_1_nom`, `c1_1_hauteur`, `c1_1_spec`, `c1_2_nom`, `c1_2_hauteur`, `c1_2_spec`, `c1_3_nom`, `c1_3_hauteur`, `c1_3_spec`, `c1_4_nom`, `c1_4_hauteur`, `c1_4_spec`, `c1_5_nom`, `c1_5_hauteur`, `c1_5_spec`, `c1_6_nom`, `c1_6_hauteur`, `c1_6_spec`, `c1_7_nom`, `c1_7_hauteur`, `c1_7_spec`, `c1_8_nom`, `c1_8_hauteur`, `c1_8_spec`, `c1_9_nom`, `c1_9_hauteur`, `c1_9_spec`, `c1_10_nom`, `c1_10_hauteur`, `c1_10_spec`, `c1_11_nom`, `c1_11_hauteur`, `c1_11_spec`, `c1_12_nom`, `c1_12_hauteur`, `c1_12_spec`, `c1_13_nom`, `c1_13_hauteur`, `c1_13_spec`, `c1_14_nom`, `c1_14_hauteur`, `c1_14_spec`, `c1_15_nom`, `c1_15_hauteur`, `c1_15_spec`, `c1_16_nom`, `c1_16_hauteur`, `c1_16_spec`, `c1_17_nom`, `c1_17_hauteur`, `c1_17_spec`, `c1_18_nom`, `c1_18_hauteur`, `c1_18_spec`, `c1_19_nom`, `c1_19_hauteur`, `c1_19_spec`, `c1_20_nom`, `c1_20_hauteur`, `c1_20_spec`, `c1_21_nom`, `c1_21_hauteur`, `c1_21_spec`, `c1_22_nom`, `c1_22_hauteur`, `c1_22_spec`, `c1_23_nom`, `c1_23_hauteur`, `c1_23_spec`, `c1_24_nom`, `c1_24_hauteur`, `c1_24_spec`, `c1_25_nom`, `c1_25_hauteur`, `c1_25_spec`) VALUES
(89, 'Clavier expressif', '56', 'Bourdon', '16\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Gambe', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Trompette', '8\\\'', 'B/D', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(90, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', 'B/D', 'Flûte harmonique', '8\\\'', '', 'Prestant', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(91, 'Clavier', '56', 'Montre', '8', NULL, 'Bourdon', '8', NULL, 'Prestant ', '4', NULL, 'Flûte', '4', NULL, 'Doublette', '2', NULL, 'Plein jeu', 'III', NULL, 'Trompette', '8', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(93, 'Grand-Orgue', '54', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Salitional', '8\\\'', 'C2', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Nasard', '2\\\'2/3', 'A#2', 'Doublette', '2\\\'', '', 'Fourniture', 'III', '', 'Trompette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(94, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Diapason', '8\\\'', '', 'Bourdon', '8\\\'', 'extension', 'Prestant', '4\\\'', 'extension', 'Doublette', '2\\\'', NULL, 'Quinte', '', NULL, 'Plein-Jeu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(95, 'Grand-Orgue', '56', 'Montre', '8\\\'', '', 'Flûte', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-Jeu', 'IV', '', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', '', 'Cromorne', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(96, 'Grand-Orgue', '54', 'Montre', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-Jeu IV', 'IV', '', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(97, 'Grand-Orgue', '56', 'Montre', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-Jeu', 'IV', '', 'Cromorne', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(98, 'Clavier expressif', '56', 'Bourdon', '16\\\'', 'B/D', 'Principal', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Prestant', '4\\\'', '', 'Trompette', '8\\\'', 'B/D', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(99, 'Grand-Orgue', '54', 'Bourdon', '16\\\'', '', 'Principal', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-Jeu', 'IV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(100, 'Grand-Orgue', '54', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Salicional', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-Jeu', 'II-V', '', 'Cornet', 'V', '', 'Bombarde', '16\\\'', '', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(101, 'Grand-Orgue', '56', 'Montre', '8\\\'', '', 'Flûte', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-Jeu', '', '', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', '', 'Cromorne', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(102, 'Positif de dos', '54', 'Bourdon', '8', NULL, 'Montre', '4', NULL, 'Flûte', '4', NULL, 'Doublette', '2', NULL, 'Nazard', '2 2/3', NULL, 'Tierce', '1 3/5', NULL, 'Plein-Jeu', 'V', NULL, 'Cromorne', '8', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(103, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(104, 'Positif', '54', 'Bourdon', '8\\\'', '', 'Montre', '4\\\'', '', 'Flûte', '4\\\'', '', 'Nazard', '2\\\'2/3', '', 'Doublette', '2\\\'', '', 'Tierce', '1\\\'3/5', '', 'Plein-Jeu', 'V', '', 'Cromorne', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(105, 'Grand Orgue', '56', 'Bourdon', '16', NULL, 'Montre', '8', NULL, 'Bourdon', '8', NULL, 'Prestant ', '4', NULL, 'Nasard ', '2 2/3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(106, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', NULL, 'Montre', '8\\\'', NULL, 'Flûte harmonique', '8\\\'', NULL, 'Bourdon', '8\\\'', NULL, 'Prestant', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(107, 'Grand-Orgue', '56', 'Flûte conique', '8\\\'', NULL, 'Prestant', '4\\\'', NULL, 'Larigot', '1\\\'1/3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(108, 'Grand-Orgue', '54', 'Bourdon', '16\\\'', NULL, 'Montre', '8\\\'', NULL, 'Bourdon', '8\\\'', NULL, 'Flûte', '8\\\'', NULL, 'Gambe ', '8\\\'', 'C3', 'Prestant', '4\\\'', NULL, 'Trompette', '8\\\'', NULL, 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(109, 'Grand Orgue', '56', 'Bourdon', '16\\\'', NULL, 'Montre', '8\\\'', NULL, 'Bourdon', '8\\\'', NULL, 'Prestant', '4\\\'', NULL, 'Doublette', '2\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(110, 'Grand-Orgue', '56', 'Montre', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', NULL, 'Cornettino', 'III', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(111, 'Grand orgue', '56', 'Bourdon', '16\\\'', NULL, 'Montre', '8\\\'', NULL, 'Bourdon', '8\\\'', NULL, 'Prestant', '4\\\'', NULL, 'Nasard', '2\\\'2/3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(112, 'Grand-Orgue', '56', 'Montre', '16\\\'', '', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Prestant', '4\\\'', '', 'Octave', '4\\\'', '', 'Flûte', '4\\\'', '', 'Plein-Jeu', 'IV', '', 'Cymbale', 'III', '', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', '', 'Cromorne', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(113, 'Grand-Orgue', '56', 'Montre', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Cornet', 'III', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(114, 'Grand-Orgue', '54', 'Bourdon', '16\\\'', '', 'Flûte', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-Jeu', 'III', '', 'Trompette', '8\\\'', 'B/D', 'Clairon', '4\\\'', 'B/D', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(115, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Salicional', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Cornet', 'III', 'C3', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(116, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', NULL, 'Montre', '8\\\'', '', 'Flûte', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-Jeu', 'IV', '', 'Cornet', 'V', 'C3', 'Trompette', '8\\\'', '', 'Clairon', '4\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(117, 'Positif', '56', 'Bourdon', '8\\\'', '', 'Flûte', '4\\\'', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(118, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', '', 'Montre', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Bourdon', '8\\\'', '', 'Prestant', '4\\\'', '', 'Flûte', '4\\\'', '', 'Doublette', '2\\\'', '', 'Plein-Jeu', 'IV', '', 'Cromorne', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(119, 'Hauptwerk', '56', 'Prinzipal', '8\\\'', NULL, 'Spitzflöte', '8\\\'', NULL, 'Oktave', '4\\\'', NULL, 'Waldflöte', '2\\\'', NULL, 'Sesquialter', 'II', NULL, 'Mixtur', 'VI', NULL, 'Holzdulzian', '16\\\'', '', 'Trompete', '8\\\'', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(121, 'Grand-Orgue', '56', 'Bourdon', '16\\\'', 'B/D', 'Montre', '8\\\'', '', 'Flûte harmonique', '8\\\'', '', 'Prestant', '4\\\'', '', 'Plein-Jeu', 'II-IV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(120, 'Grand-Orgue', '56', 'Flûte', '8\\\'', NULL, 'Prestant', '4\\\'', NULL, 'Doublette', '2\\\'', NULL, 'Sesquialter', 'II', 'Quinte séparable', 'Cymbale', 'II', NULL, '', '', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(122, 'Grand Orgue', NULL, 'Bourdon', '16', NULL, 'Montre', '8', NULL, 'Bourdon ', '8', NULL, 'Flûte harmonique ', '8', NULL, 'Salicional', '8', NULL, 'Prestant', '4', NULL, 'Nasard', '2 2/3', NULL, 'Plein jeu', 'II/V rangs', 'emprunte le nasard', 'Trompette', '8', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(123, 'Grand-Orgue', '61', 'Montre', '8\\\'', '', 'Flûte harmonique', '8\\\'', NULL, 'Bourdon', '8\\\'', NULL, 'Prestant', '4\\\'', NULL, 'Doublette', '2\\\'', NULL, 'Plein-Jeu 16\\\'', 'I', NULL, 'Plein-Jeu 8\\\'', 'IV', NULL, 'Cornet', 'V', NULL, 'Trompette', '8\\\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(125, 'Récit expressif', '56', 'Principal', '8\'', 'B/D', 'Flûte', '8\'', 'B/D', 'Viola da Gamba', '8\'', '', 'Voce umana', '8\'', 'D', 'Principal', '4\'', 'B/D', 'Flûte', '4\'', 'B/D', 'Doublette', '2\'', '', 'Flageolet', '2\'', '', 'Fourniture', 'III', '', 'Cymbale', 'II', '', 'Cornet', 'II rangs', 'D', 'Corno Inglese', '16\'', 'D', 'Basson', '8\'', 'B', 'Hautbois', '8\'', 'D', 'Voix humaine', '8\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(126, 'Grand-Orgue', '56', 'Montre', '8\'', NULL, 'Flûte harmonique', '8\'', NULL, 'Prestant', '4\'', NULL, 'Plein-Jeu', 'III', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(127, 'Clavier', '54', 'Montre', '8\'', 'B/D', 'Bourdon', '8\'', '', 'Flûte harmonique', '8\'', '', 'Gambe', '8\'', '', 'Voix céleste', '8\'', 'C2', 'Prestant', '4\'', '', 'Doublette', '2\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(128, '1er clavier', '61', 'Principal', '8\'', 'C1-H1 = Bourdon 8\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(130, 'Grand-Orgue', '54', 'Bourdon', '16\'', '', 'Montre', '8\'', '', 'Flûte harmonique', '8\'', '', 'Bourdon', '8\'', '', 'Prestant', '4\'', '', 'Nasard', '2\'2/3', '', 'Plein-Jeu', 'III', '', 'Cornet', 'II-V', '', 'Trompette', '8\'', '', 'Clairon', '4\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(131, 'Grand-Orgue', '54', 'Bourdon', '16\'', '', 'Montre', '8\'', '', 'Flûte', '8\'', '', 'Violoncelle', '8\'', '', 'Bourdon', '8\'', '', 'Prestant', '4\'', '', 'Doublette', '2\'', '', 'Plein-Jeu', 'I-IV', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(132, 'Positif', '53', 'Montre', '8\'', '', 'Bourdon', '8\'', '', 'Prestant', '4\'', '', 'Nasard', '2\'2/3', '', 'Doublette', '2\'', '', 'Tierce', '1\'3/5', '', 'Fourniture', '', '', 'Cromorne', '8\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(133, 'Grand-Orgue', '56', 'Bourdon', '16\'', '', 'Montre', '8\'', '', 'Bourdon', '8\'', '', 'Prestant', '4\'', '', 'Doublette', '2\'', '', 'Larigot', '1\'1/3', '', 'Fourniture', 'IV', '', 'Trompette', '8\'', '', 'Clairon', '4\'', '', 'Cromorne', '8\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(134, '1er Clavier', '61', 'Bourdon ', '8\'', 'C1-H1 électroniques', 'Flûte conique', '4\'', 'extension', 'Nasard ', '2\'2/3', 'extension', 'Flûte', '2', 'extension', 'Larigot', '1\'1/3', 'extension', 'Piccolo', '1\'', 'extension', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(135, 'Clavier expressif', '56', 'Bourdon', '16\'', 'D', 'Violoncelle', '8\'', 'B/D', 'Bourdon', '8\'', 'B', 'Flûte harmonique', '8\'', 'D', 'Voix céleste', '8\'', 'D', 'Flûte octaviante', '4\'', 'B/D', 'Trompette', '8\'', 'B/D', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(136, 'Clavier expressif', '56', 'Bourdon', '16\'', 'B/D 1ère octave acoustique', 'Bourdon', '8\'', 'B/D', 'Flûte harmonique', '8\'', 'D', 'Violoncelle', '8\'', 'B/D', 'Voix céleste', '8\'', 'D', 'Flûte', '4\'', 'B/D', 'Trompette', '8\'', 'B/D', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(137, 'Clavier expressif', '56', 'Bourdon', '16\'', 'D', 'Bourdon', '8\'', 'B', 'Flûte harmonique', '8\'', 'D', 'Violoncelle', '8\'', 'B/D', 'Voix céleste', '8\'', 'D', 'Flûte octaviante', '4\'', 'B/D', 'Octavin', '2\'', 'B/D', 'Trompette', '8\'', 'B/D', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(138, 'Grand-Orgue', '56', 'Montre', '8\'', '', 'Bourdon', '8\'', '', 'Prestant', '4\'', '', 'Doublette', '2\'', '', 'Mixture', 'II-III', NULL, 'Cromorne', '8\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(139, 'Grand Orgue expressif', '56', 'Montre', '8\'', '', 'Flûte', '8\'', '', 'Prestant', '4\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(140, 'Grand-Orgue expressif ', '54', 'Bourdon', '16\'', '', 'Montre', '8\'', '', 'Bourdon', '8\'', '', 'Gambe', '8\'', '', 'Voix céleste', '8\'', NULL, 'Prestant', '4\'', '', 'Doublette', '2\'', '', 'Trompette', '8\'', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(141, 'Grand-Orgue', '56', 'Bourdon', '16\'', '', 'Bourdon', '8\'', 'extension', 'Montre', '8\'', '', 'Prestant', '4\'', '', 'Doublette', '2\'', '', 'Plein-jeu', 'III', '', 'Trompette', '8\'', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(142, 'Grand-Orgue', '56', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(143, 'Grand-Orgue', '56', 'Bourdon', '16\'', '', 'Montre', '8\'', '', 'Flûte harmonique', '8\'', '', 'Bourdon', '8\'', NULL, 'Prestant', '4\'', '', 'Flûte douce', '4\'', '', 'Doublette', '2\'', '', 'Cornettino', 'III', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(144, 'Grand-Orgue', '56', 'Bourdon', '16\'', '', 'Montre', '8\'', '', 'Flûte', '8\'', '', 'Bourdon', '8\'', '', 'Prestant', '4\'', '', 'Doublette', '2\'', '', 'Plein-jeu', 'IV', '', 'Cromorne', '8\'', 'en attente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(145, 'Clavier expressif', '56', 'Bourdon', '16\'', 'D', 'Bourdon', '8\'', 'B/D', 'Violoncelle', '8\'', 'B/D', 'Voix céleste', '8\'', 'D', 'Flûte octaviante', '4\'', 'B/D', 'Trompette', '8\'', 'B/D', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(147, 'Grand-Orgue', '54', 'Bourdon', '16\'', '', 'Montre', '8\'', '', 'Bourdon', '8\'', '', 'Prestant', '4\'', '', 'Flûte', '4\'', '', 'Doublette', '2\'', '', 'Plein-Jeu', 'IV', '', 'Trompette', '8\'', '', 'Clairon', '4\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(146, 'Grand-Orgue', '56', 'Montre', '8\'', '', 'Bourdon', '8\'', '', 'Prestant', '4\'', '', 'Doublette', '2\'', '', 'Fourniture', 'IV-V', '', 'Trompette', '8\'', '', 'Cromorne', '8\'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(148, 'Grand-Orgue expressif', '56', 'Bourdon', '16\'', '', 'Principal', '8\'', '', 'Salicional', '8\'', '', 'Bourdon', '8\'', '', 'Prestant', '4\'', '', 'Doublette', '2\'', '', 'Plein-Jeu', 'III', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(149, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(150, 'Grand Orgue', '61', 'Montre', '8', NULL, 'Flûte harmonique', '8', NULL, 'Principal', '4', NULL, 'Mixture', '', NULL, 'Trompette', '8', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(151, 'Premier clavier', '61', 'Principal', '8\'', '', 'Flûte', '8\'', '', 'Prestant', '4\'', '= Principal', 'Flûte', '4\'', '= Flûte', 'Quinte', '2\'2/3', '= Principal', 'Doublette', '2\'', '= Principal', 'Tierce', '1\'3/5', 'C3', 'Larigot', '1\'1/3', '= Principal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(152, 'Clavier transpositeur', '56', 'Bourdon', '16', 'dessus', 'Bourdon', '8', 'basses', 'Flûte harmonique', '8', 'dessus', 'Violoncelle', '8', 'basses et dessus', 'Voix céleste', '8', 'dessus', 'Flüte octaviante', '4', 'basses et dessus', 'Trompette', '8', 'basses et dessus', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `inventaire_clavier1`
--
ALTER TABLE `inventaire_clavier1`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `id` (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `inventaire_clavier1`
--
ALTER TABLE `inventaire_clavier1`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=153;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
